
version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file sam-template.yaml --s3-bucket zak-test-bucket --output outputSamTemplate.yaml                              
artifacts:
  type: zip
  files:
    - sam-template.yaml
    - outputSamTemplate.yaml
   
