version: 0.2
phases:
  build:
    commands:
      - pip install awscli --upgrade --user
      - aws cloudformation package --template-file sam-template.yaml --s3-bucket zak-test-bucket 
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  files:
    - '**/*'
   
