AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Books:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      CodeUri: ./
      Handler: currentTimeLambda.handler
      Layers:
        - !Ref LambdaLayerDemo
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectACL
              Resource: '*'
  LambdaLayerDemo:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: MyLayer12
      Description: Layer description
      ContentUri: 's3://idh-lambda-test-bucket/momentjs-lambda-layer.zip'
      CompatibleRuntimes:
        - nodejs6.10
        - nodejs8.10
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Retain
