AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Books:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      CodeUri: ./
      Handler: currentTimeLambda.handler
      Layers:
        - !Ref LambdaLayerDemo
      Role: arn:aws:iam::451063263679:role/idh-lambda-s3-iam-role
  LambdaLayerDemo:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: MyLayer12
      Description: Layer description
      ContentUri: 's3://zak-test-bucket/momentjs-lambda-layer.zip'
      CompatibleRuntimes:
        - nodejs6.10
        - nodejs8.10
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Retain
